// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVekAtAPHJxmVnnVk7RAFC1IZ7Ly9GqtQ',
    appId: '1:959171514429:web:55dc7da49042cfb07e1a54',
    messagingSenderId: '959171514429',
    projectId: 'mottu-marvel',
    authDomain: 'mottu-marvel.firebaseapp.com',
    storageBucket: 'mottu-marvel.appspot.com',
    measurementId: 'G-J7FBDFD0J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAplYpOW-sQOW4k3A5aWiiefIFVJMp0qWA',
    appId: '1:959171514429:android:4a9263132c08222e7e1a54',
    messagingSenderId: '959171514429',
    projectId: 'mottu-marvel',
    storageBucket: 'mottu-marvel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByI9RYzpetJz2AAIscT8nPLLQcVwvZ1cM',
    appId: '1:959171514429:ios:092219f265babc247e1a54',
    messagingSenderId: '959171514429',
    projectId: 'mottu-marvel',
    storageBucket: 'mottu-marvel.appspot.com',
    iosClientId: '959171514429-0q70tt3a7l6gipd99jb0rfgthctfkapd.apps.googleusercontent.com',
    iosBundleId: 'com.mottu.marvel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByI9RYzpetJz2AAIscT8nPLLQcVwvZ1cM',
    appId: '1:959171514429:ios:e6003d1804d31f087e1a54',
    messagingSenderId: '959171514429',
    projectId: 'mottu-marvel',
    storageBucket: 'mottu-marvel.appspot.com',
    iosClientId: '959171514429-02heplsmlpqiiaqt2c6rt3ioe46hb68s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mottuMarvel',
  );
}
